##
##  Specification Book (SpecBook)
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under Apache 2.0 <https://spdx.org/licenses/Apache-2.0>
##

#   [web] lint project (type-check and static code analysis)
lint
    astro check --config etc/astro.config.mjs && \
    eslint --config etc/eslint.mjs "src/**/*.{ts,astro}"

#   [web] build project
build : lint
    astro build --config etc/astro.config.mjs

#   [web] development target
dev
    astro dev --config etc/astro.config.mjs

#   [web] preview website
preview
    astro preview --config etc/astro.config.mjs

#   [web] remove website
clean
    shx rm -rf dst

#   [web] remove all built files
distclean: clean
    shx rm -f package-lock.json
    shx rm -rf node_modules
