##
##  Specification Book (SpecBook)
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under Apache 2.0 <https://spdx.org/licenses/Apache-2.0>
##

#   [tool] static code analysis (linting)
lint
    eslint --config etc/eslint.mjs src/*.ts

#   [tool] static code analysis (linting) with file watching
lint-watch
    nodemon --exec "npm start lint" --watch src --ext ts

#   [tool] code compilation/transpiling (building) with file watching
build-watch
    nodemon --exec "npm start build" --watch src --ext ts

#   [tool] build entire project
build : lint build-cmd

#   [tool] build command program
build-cmd
    tsc --project etc/tsconfig.json
    postcss src/specbook-export-html.css --config etc --output dst/specbook-export-html.css
    shx cp src/specbook-export-html-search.js dst/specbook-export-html-search.js
    shx cp src/specbook-format.md dst/specbook-format.md
    shx cp src/specbook-format.yaml dst/specbook-format.yaml
    shx cp etc/specbook-logo-blue-light.svg dst/specbook-export-logo-light.svg
    shx cp etc/specbook-logo-blue-dark.svg  dst/specbook-export-logo-dark.svg

#   publish to github.com and npmjs.com
publish [hostname={en4.*,MSGMAC-M2M79300K6}]
    increment="patch"; \
    case "$*" in -i* ) increment=`echo "$*" | sed -e 's;^-i;;'` ;; esac; \
    kickout "$increment" && \
    VERSION=`sed -n '/"version":/ s/.*: *"\(.*\)".*/\1/p' package.json` && \
    V=`echo "$VERSION" | sed -e 's;\.;\\.;g'` && \
    sed -n -e "/^${V} /, /^[0-9]\\./ { /^${V} /p; /^[0-9]\\./!p; }" <CHANGELOG.md >.notes.md && \
    gh release create --title "SpecBook $VERSION" --notes-file .notes.md --verify-tag $VERSION && \
    rm -f .notes.md

#   [tool] sample
sample : sample-broadcast sample-sample

#   [tool] lint and export the sample "broadcast" specification
sample-broadcast
    node dst/specbook-cli.js lint \
        --verbose \
        -b smp/broadcast && \
    node dst/specbook-cli.js export \
        --verbose \
        -b smp/broadcast \
        -o smp/broadcast.md \
        -o smp/broadcast.json \
        -o smp/broadcast.json5 \
        -o smp/broadcast.yaml \
        -o smp/broadcast.toon \
        -o smp/broadcast.html \
        -o smp/broadcast.pdf && \
    node dst/specbook-cli.js describe \
        --verbose \
        -c src/specbook-format.yaml \
        -b smp/broadcast \
        -o smp/broadcast-describe.md

#   [tool] lint and export the sample "broadcast" specification
sample-sample
    node dst/specbook-cli.js lint \
        --verbose \
        -c smp/sample/sample.yaml \
        -b smp/sample/ && \
    node dst/specbook-cli.js export \
        --verbose \
        -c smp/sample/sample.yaml \
        -b smp/sample/ \
        -o smp/sample/sample.html \
        -o smp/sample/sample.pdf

#   [tool] remove regularly built files
clean
    shx rm -rf dst
    shx rm -f smp/broadcast.json smp/broadcast.json5 smp/broadcast.yaml \
        smp/broadcast.toon smp/broadcast.html smp/broadcast.pdf smp/broadcast.md

#   [tool] remove all built files
distclean : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

