##
##  Specification Book (SpecBook)
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under Apache 2.0 <https://spdx.org/licenses/Apache-2.0>
##

#   [tool] static code analysis (linting)
lint
    eslint --config etc/eslint.mjs src/*.ts

#   [tool] static code analysis (linting) with file watching
lint-watch
    nodemon --exec "npm start lint" --watch src --ext ts

#   [tool] code compilation/transpiling (building) with file watching
build-watch
    nodemon --exec "npm start build" --watch src --ext ts

#   [tool] build entire project
build : lint build-cmd

#   [tool] build command program
build-cmd
    tsc --project etc/tsconfig.json
    postcss src/specbook-export-html.css --config etc --output dst/specbook-export-html.css
    shx cp src/specbook-export-html-search.js dst/specbook-export-html-search.js
    shx cp src/specbook-format.md dst/specbook-format.md
    shx cp etc/specbook-logo.svg dst/specbook-export-logo.svg

#   [tool] lint and export the sample specification
sample : build
    node dst/specbook-cli.js lint \
        --verbose \
        -c smp/ase.specbook.yaml \
        -b smp/broadcast || true
    node dst/specbook-cli.js export \
        -c smp/ase.specbook.yaml \
        -b smp/broadcast \
        -o smp/broadcast.md \
        -o smp/broadcast.json \
        -o smp/broadcast.json5 \
        -o smp/broadcast.yaml \
        -o smp/broadcast.toon \
        -o smp/broadcast.html \
        -o smp/broadcast.pdf
    node dst/specbook-cli.js describe \
        -c smp/ase.specbook.yaml \
        -b smp/broadcast \
        -o smp/broadcast-describe.md

#   [tool] remove regularly built files
clean
    shx rm -rf dst
    shx rm -f smp/broadcast.json smp/broadcast.json5 smp/broadcast.yaml \
        smp/broadcast.toon smp/broadcast.html smp/broadcast.pdf smp/broadcast.md

#   [tool] remove all built files
distclean : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

